# Generated by Django 4.2.30 on 2026-09-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.seekerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('seeker', 'job')},
        ),
    ]
