# Generated by Django 4.2.30 on 2026-10-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
