# Generated by Django 4.2.30 on 2026-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20),
        ),
    ]
