# Generated by Django 4.2.30 on 2026-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_country_jobposting_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
