# Generated by Django 4.2.30 on 2026-09-18 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.PositiveSmallIntegerField(default=3)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.seekerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'unique_together': {('seeker', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(related_name='seekers', through='profiles.SeekerSkill', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
