# Generated by Django 4.2.30 on 2026-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
