# Generated by Django 4.2.30 on 2026-10-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_seekerprofile_resume_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
