# Generated by Django 4.2.30 on 2026-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_seekerprofile_resume_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
